# This Docker Compose file comes from the Postgres Docker documentation:
# https://github.com/docker-library/docs/blob/master/postgres/README.md#-via-docker-compose-or-docker-stack-deploy

version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./src/system/db/sql/database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./src/system/db/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./src/system/db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql