# This Docker Compose file comes from the Postgres Docker documentation:
# https://github.com/docker-library/docs/blob/master/postgres/README.md#-via-docker-compose-or-docker-stack-deploy
#

version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - 5433:5432
    volumes:
      - ./system/db/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./system/db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql